### PR TITLE
Testnet deployments

### PR DESCRIPTION
**Pull request by tbwebb22**
This PR updates deployments of the contract to Goerli and Sepolia testnets

### CODE REVIEW

**Review by christopherdancy — APPROVED** [review]
This is good. The question is - should different chains have the same metafactory address?

**Comment by christopherdancy** [comment]
@adamgall should this be the case? Should we take the time to change the nonce or carry out the create2 opcode for deployments?

**Comment by adamgall** [comment]
> @adamgall should this be the case? Should we take the time to change the nonce or carry out the create2 opcode for deployments? 

I don't think I have enough context to have much of an opinion on this. What do you guys think is best?

**Comment by tbwebb22** [comment]
> > @adamgall should this be the case? Should we take the time to change the nonce or carry out the create2 opcode for deployments?
> 
> I don't think I have enough context to have much of an opinion on this. What do you guys think is best?

In my opinion, there isn't a need for any contract changes here. For final deployments of testnet and mainnet contracts, we can just be sure to use a fresh account so that addresses across testnets are the same for implementation and factory contracts.

**Comment by adamgall** [comment]
@tbwebb22 all good

In the future, we can take notes from Seaport's deployment patterns to simplify and standardize same-address deployments across chains.

https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md

**Pull request merged**
